### ISSUE TITLE
What in the actual heck, null values??

### ISSUE THREAD

**Issue by Traehgniw** [spacechase0/CustomizeExterior#2]
https://smapi.io/log/ba03af6235ac4541a60ecc1046ea0452

SpriteMaster errors revealing some bafflingly messed up stuff here; your graphics device sampler state is null, which should never happen ever. This only affects the house and greenhouse.

**Comment by spacechase0** [comment]
Problem with SpriteMaster. Try not to be so aggressive :P

**Comment by Traehgniw** [comment]
(I was pretty much quoting Ameise's initial reactions to finding a null error there)
